### ISSUE TITLE
7 tests fail on stable-x86_64-apple-darwin - 1.53.0 (53cb7b09b 2021-06-17)

### ISSUE THREAD

**Issue by jayvdb** [sagiegurari/duckscript#185]
### Describe The Bug
I am seeing the following errors running `cargo test` on latest stable and nightly:
-  sdk::std::fs::append::mod_test::run_not_exists
-   sdk::std::fs::mv::mod_test::run_directory_to_directory
-   sdk::std::fs::mv::mod_test::run_file_to_directory
-   sdk::std::fs::mv::mod_test::run_file_to_file
-   utils::io::io_test::create_empty_file_exists
-   utils::io::io_test::create_empty_file_not_exists
-   utils::io::io_test::write_to_text_file_not_exists

### To Reproduce
1. rustup update
2. cargo test

```rust
failures:

---- sdk::std::fs::mv::mod_test::run_file_to_directory stdout ----
on error: [
    "Path \"./target/_duckscript/mv/run_file_to_directory/2/file1.txt\" is exist",
    "2",
    "",
]
thread 'sdk::std::fs::mv::mod_test::run_file_to_directory' panicked at 'assertion failed: context.variables.get(&\"on_error_invoked\".to_string()).is_none()', duckscript_sdk/src/test/mod.rs:259:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- sdk::std::fs::mv::mod_test::run_file_to_file stdout ----
on error: [
    "Path \"./target/_duckscript/mv/run_file_to_file/2/file2.txt/file1.txt\" is exist",
    "2",
    "",
]
thread 'sdk::std::fs::mv::mod_test::run_file_to_file' panicked at 'assertion failed: context.variables.get(&\"on_error_invoked\".to_string()).is_none()', duckscript_sdk/src/test/mod.rs:259:13

---- sdk::std::fs::mv::mod_test::run_directory_to_directory stdout ----
on error: [
    "Path \"./target/_duckscript/mv/run_directory_to_directory/2/1/1/file1.txt\" is exist",
    "2",
    "",
]
thread 'sdk::std::fs::mv::mod_test::run_directory_to_directory' panicked at 'assertion failed: context.variables.get(&\"on_error_invoked\".to_string()).is_none()', duckscript_sdk/src/test/mod.rs:259:13

---- sdk::std::fs::append::mod_test::run_not_exists stdout ----
thread 'sdk::std::fs::append::mod_test::run_not_exists' panicked at 'assertion failed: `(left == right)`
  left: `"line 1\nline 2line 1\nline 2"`,
 right: `"line 1\nline 2"`', duckscript_sdk/src/sdk/std/fs/append/./mod_test.rs:32:5

---- utils::io::io_test::create_empty_file_exists stdout ----
thread 'utils::io::io_test::create_empty_file_exists' panicked at 'assertion failed: !file_path.exists()', duckscript_sdk/src/utils/./io_test.rs:92:5

---- utils::io::io_test::create_empty_file_not_exists stdout ----
thread 'utils::io::io_test::create_empty_file_not_exists' panicked at 'assertion failed: !file_path.exists()', duckscript_sdk/src/utils/./io_test.rs:80:5

---- utils::io::io_test::write_to_text_file_not_exists stdout ----
thread 'utils::io::io_test::write_to_text_file_not_exists' panicked at 'assertion failed: `(left == right)`
  left: `"test file\ntest filetest file\ntest file"`,
 right: `"test file\ntest file"`', duckscript_sdk/src/utils/./io_test.rs:73:5


failures:
    sdk::std::fs::append::mod_test::run_not_exists
    sdk::std::fs::mv::mod_test::run_directory_to_directory
    sdk::std::fs::mv::mod_test::run_file_to_directory
    sdk::std::fs::mv::mod_test::run_file_to_file
    utils::io::io_test::create_empty_file_exists
    utils::io::io_test::create_empty_file_not_exists
    utils::io::io_test::write_to_text_file_not_exists

test result: FAILED. 785 passed; 7 failed; 3 ignored; 0 measured; 0 filtered out; finished in 24.20s

error: test failed, to rerun pass '-p duckscriptsdk --lib'
```

**Comment by sagiegurari** [comment]
you must run it via cargo make as defined i the contribute doc
